### ISSUE TITLE
errors with Debian 11.3

### ISSUE THREAD

**Issue by stefangweichinger** [AmadeusITGroup/monitoring-plugins#5]
Are these plugins expected to work with latest Debian 11.3?

I tried to execute `check_dkim.pl` and get errors around loading the needed modules:

```
# ./check_dkim.pl
Can't call method "import" on an undefined value at ./check_dkim.pl line 36.
BEGIN failed--compilation aborted at ./check_dkim.pl line 43.
```

**Comment by t-8ch** [comment]
Do you have `libmonitoring-plugin-perl` installed?

**Comment by stefangweichinger** [comment]
@t-8ch my fault, yes, that "fixed" it. Sorry for the noise.

**Comment by t-8ch** [comment]
Do you have libmonitoring-plugin-perl installed?

**Comment by stefangweichinger** [comment]
I closed this in May already. Thanks again.
